Add sha256 support with old md5 support
kuzzleio/kuzzle-vault pull request #3
Opened 2019-09-16 16:21 UTC by Shiranuit

## What does this PR do ?

The goal of this PR is to avoid using `MD5` hashes in hexadecimal format as a key for `aes-256-cbc` because even if they are 32 bytes long, which should give us 256 bits password entropy `(256^32 == 2^256).`
But since we know that there would only be hexadecimal characters within the 32 bytes so it reduce the password entropy to 128 bits `(16^32 == 2^128)`.
So we use a 256 bits password to encrypt data but we only have a 128 bits for the password entropy.

This is why this PR use `SHA256` instead of `MD5`, to provide 256 bits length password and 256 bits of password entropy, and also support old `MD5` hashed keys to decrypt data.

2019-09-16 17:09 UTC, Aschen commented
More an `enhancement` to me

2019-09-16 17:10 UTC, Aschen requested changes
Please add an unit test with an AES hash

2019-09-17 09:47 UTC, scottinet approved these changes

2019-09-17 15:10 UTC, Aschen approved these changes

2019-09-18 07:51 UTC, merged